/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbo.latihangui;

import java.util.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author User
 */
public class ListSetMapGUI extends javax.swing.JFrame {

    /**
     * Creates new form SaveJListGUI
     */
    
    DefaultListModel<String> dlm;
    List<String> itemList = new ArrayList<>();
    Set<String> itemSet = new HashSet<>();
    Map<String, String> itemMap = new HashMap<>();
    
    String[] datas = {"buku", "meja", "kursi", "tas", "pintu"};
    
    public ListSetMapGUI() {
        initComponents();
        dlm = new DefaultListModel<>();
        ItemList.setModel(dlm);
        
        for (String data : datas) {
            dlm.addElement(data);
            updateJumDataTersimpan();
        }
    }
    private void addItem(String namaItem) {
        dlm.addElement(namaItem);
    }
    
    private void updateJumDataTersimpan() {
        DataListLabel.setText("Data Tersimpan = " + itemList.size());
        DataSetLabel.setText("Data Tersimpan = " + itemSet.size());
        DataMapLabel.setText("Data Tersimpan = " + itemMap.size());
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ItemList = new javax.swing.JList<>();
        InsertListButton = new javax.swing.JButton();
        SaveListButton = new javax.swing.JButton();
        DataListLabel = new javax.swing.JLabel();
        InputText = new javax.swing.JTextField();
        ItemNameLabel = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        DataSetLabel = new javax.swing.JLabel();
        SaveSetButton = new javax.swing.JButton();
        InsertSetButton = new javax.swing.JButton();
        DataMapLabel = new javax.swing.JLabel();
        SaveMapButton = new javax.swing.JButton();
        InsertMapButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ItemList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ItemList);

        InsertListButton.setText("Insert data List");
        InsertListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertListButtonActionPerformed(evt);
            }
        });

        SaveListButton.setText("Save to List");
        SaveListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveListButtonActionPerformed(evt);
            }
        });

        DataListLabel.setText("Data Tersimpan = 0");

        ItemNameLabel.setText("Item Name:");

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        DataSetLabel.setText("Data Tersimpan = 0");

        SaveSetButton.setText("Save to Set");
        SaveSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveSetButtonActionPerformed(evt);
            }
        });

        InsertSetButton.setText("Insert data Set");
        InsertSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertSetButtonActionPerformed(evt);
            }
        });

        DataMapLabel.setText("Data Tersimpan = 0");

        SaveMapButton.setText("Save to Map");
        SaveMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMapButtonActionPerformed(evt);
            }
        });

        InsertMapButton.setText("Insert data Map");
        InsertMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMapButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SaveSetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InsertSetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGap(23, 23, 23)
                                .addComponent(DataSetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SaveMapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InsertMapButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGap(23, 23, 23)
                                .addComponent(DataMapLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ItemNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SaveListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InsertListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(InputText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(DataListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ClearButton)
                        .addGap(38, 38, 38)
                        .addComponent(AddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveListButton)
                            .addComponent(DataListLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsertListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveSetButton)
                            .addComponent(DataSetLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsertSetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveMapButton)
                            .addComponent(DataMapLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsertMapButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemNameLabel)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClearButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddButton)
                        .addComponent(DeleteButton)
                        .addComponent(UpdateButton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int index = ItemList.getSelectedIndex();
        dlm.removeElementAt(index);
        
        InputText.setText("");    
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void InsertListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertListButtonActionPerformed
        for (String item : itemList) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_InsertListButtonActionPerformed

    private void SaveListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveListButtonActionPerformed
        if (!itemList.isEmpty()){
            itemList.clear();
        }
        
        for (int i = 0; i < dlm.getSize(); i++){
            itemList.add(dlm.getElementAt(i));
        }
        
        updateJumDataTersimpan();
    }//GEN-LAST:event_SaveListButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        addItem(InputText.getText());
        
        InputText.setText("");
    }//GEN-LAST:event_AddButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        int index = ItemList.getSelectedIndex();
        String selected = InputText.getText();
        dlm.setElementAt(selected, index);
        
        InputText.setText("");                          
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        dlm.clear();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void SaveSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveSetButtonActionPerformed
        if (!itemSet.isEmpty()){
            itemSet.clear();
        }
        
        for (int i = 0; i < dlm.getSize(); i++){
            itemSet.add(dlm.getElementAt(i));
        }
        
        updateJumDataTersimpan();
    }//GEN-LAST:event_SaveSetButtonActionPerformed

    private void InsertSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertSetButtonActionPerformed
        for (String item : itemSet) {
            dlm.addElement(item);
        }
        
        updateJumDataTersimpan();
    }//GEN-LAST:event_InsertSetButtonActionPerformed

    private void SaveMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMapButtonActionPerformed
        if (!itemMap.isEmpty()){
            itemMap.clear();
        }
        
        for (int i = 0; i < dlm.getSize(); i++){
            String key = "Item " + (i + 1);
            String value = dlm.getElementAt(i);
            itemMap.put(key, value);
        }
        
        updateJumDataTersimpan();
    }//GEN-LAST:event_SaveMapButtonActionPerformed

    private void InsertMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMapButtonActionPerformed
        for (Map.Entry<String, String> entry : itemMap.entrySet()) {
            String key = entry.getKey();
            String value = entry.getValue();
            dlm.addElement(key + ": " + value);
        }
        
        updateJumDataTersimpan();
    }//GEN-LAST:event_InsertMapButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListSetMapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListSetMapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListSetMapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListSetMapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListSetMapGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel DataListLabel;
    private javax.swing.JLabel DataMapLabel;
    private javax.swing.JLabel DataSetLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField InputText;
    private javax.swing.JButton InsertListButton;
    private javax.swing.JButton InsertMapButton;
    private javax.swing.JButton InsertSetButton;
    private javax.swing.JList<String> ItemList;
    private javax.swing.JLabel ItemNameLabel;
    private javax.swing.JButton SaveListButton;
    private javax.swing.JButton SaveMapButton;
    private javax.swing.JButton SaveSetButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
