/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program;

import java.util.List;

import javax.swing.DefaultListModel;
import model.Mahasiswa;
import service.MysqlMahasiswaService;

/**
 *
 * @author User
 */
public class JFrameUtama extends javax.swing.JFrame {

    /**
     * Creates new form JFrameUtama
     */
    DefaultListModel<String> dlmID;
    DefaultListModel<String> dlmNama;
    private MysqlMahasiswaService mahasiswaService;

    public JFrameUtama() {
        initComponents();
        dlmID = new DefaultListModel<>();
        dlmNama = new DefaultListModel<>();
        idList.setModel(dlmID);
        namaList.setModel(dlmNama);
        mahasiswaService = new MysqlMahasiswaService();
        idList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            if (!evt.getValueIsAdjusting()) {
                int selectedIndex = idList.getSelectedIndex();
                if (selectedIndex != -1) {
                    // Get the selected ID and name
                    String selectedID = dlmID.getElementAt(selectedIndex);
                    String selectedNama = dlmNama.getElementAt(selectedIndex);
                    
                    // Set values for edit fields
                    idEdit.setText(selectedID);
                    namaEdit.setText(selectedNama);
                    
                    // Set values for delete fields
                    idDelete.setText(selectedID);
                    namaDelete.setText(selectedNama);
                }
            }
        }});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        idList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        namaList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        ambilSemuaDataButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        idEdit = new javax.swing.JTextField();
        namaEdit = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        idDelete = new javax.swing.JTextField();
        namaDelete = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        idList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(idList);

        jLabel2.setText("Nama");

        namaList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(namaList);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Kelola Data Mahasiswa");

        ambilSemuaDataButton.setText("Ambil Semua Data");
        ambilSemuaDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambilSemuaDataButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama:");

        namaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaInputActionPerformed(evt);
            }
        });

        AddButton.setText("Tambahkan");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        idEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEditActionPerformed(evt);
            }
        });

        namaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaEditActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        idDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDeleteActionPerformed(evt);
            }
        });

        namaDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaDeleteActionPerformed(evt);
            }
        });

        deleteButton.setText("Hapus");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset indeks");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaInput)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ambilSemuaDataButton))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(namaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(namaDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteButton))
                            .addComponent(resetButton))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ambilSemuaDataButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(resetButton)
                        .addGap(15, 15, 15))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        String nama = namaInput.getText();
        if (!nama.isEmpty()) {
            // Create new Mahasiswa object
            Mahasiswa mhs = new Mahasiswa();
            mhs.setNama(nama);
            
            // Add to database
            mahasiswaService.add(mhs);
            System.out.println("Added to database: " + nama);
            
            // Refresh list from database
            ambilSemuaDataButtonActionPerformed(evt);
            
            // Clear input field
            namaInput.setText("");
        } else {
            System.out.println("Nama cannot be empty");
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void idEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEditActionPerformed
   
    }//GEN-LAST:event_idEditActionPerformed

    private void idDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDeleteActionPerformed
        
    }//GEN-LAST:event_idDeleteActionPerformed

    private void ambilSemuaDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambilSemuaDataButtonActionPerformed
        // Load all data from database
        List<Mahasiswa> mahasiswaList = mahasiswaService.getAll();
        
        // Clear current lists
        dlmID.clear();
        dlmNama.clear();
        
        // Populate lists with database data
        for (Mahasiswa mhs : mahasiswaList) {
            dlmID.addElement("ID" + mhs.getId());
            dlmNama.addElement(mhs.getNama());
        }
        
        System.out.println("Data loaded from database: " + mahasiswaList.size() + " records");
    }//GEN-LAST:event_ambilSemuaDataButtonActionPerformed

    private void namaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaInputActionPerformed
        String nama = namaInput.getText();
        if (!nama.isEmpty()) {
            dlmID.addElement("ID" + (dlmID.getSize() + 1)); // Auto-generate ID
            dlmNama.addElement(nama);
            System.out.println("Added Nama: " + nama);
            namaInput.setText(""); // Clear input field after action
        } else {
            System.out.println("Nama cannot be empty");
        }

    }//GEN-LAST:event_namaInputActionPerformed

    private void namaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaEditActionPerformed
        
    }//GEN-LAST:event_namaEditActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        String idText = idEdit.getText();
        String nama = namaEdit.getText();
        
        if (!idText.isEmpty() && !nama.isEmpty()) {
            try {
                // Extract numeric ID from "ID123" format
                int id = Integer.parseInt(idText.replace("ID", ""));
                
                // Create Mahasiswa object with updated data
                Mahasiswa mhs = new Mahasiswa(id, nama);
                
                // Update in database
                mahasiswaService.update(mhs);
                System.out.println("Updated in database: ID=" + id + ", Nama=" + nama);
                
                // Refresh list from database
                ambilSemuaDataButtonActionPerformed(evt);
                
                // Clear input fields
                idEdit.setText("");
                namaEdit.setText("");
            } catch (NumberFormatException e) {
                System.out.println("Invalid ID format");
            }
        } else {
            System.out.println("ID and Nama cannot be empty");
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void namaDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaDeleteActionPerformed
        
    }//GEN-LAST:event_namaDeleteActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String idText = idDelete.getText();
        
        if (!idText.isEmpty()) {
            try {
                // Extract numeric ID from "ID123" format
                int id = Integer.parseInt(idText.replace("ID", ""));
                
                // Delete from database
                mahasiswaService.delete(id);
                System.out.println("Deleted from database: ID=" + id);
                
                // Refresh list from database
                ambilSemuaDataButtonActionPerformed(evt);
                
                // Clear input fields
                idDelete.setText("");
                namaDelete.setText("");
            } catch (NumberFormatException e) {
                System.out.println("Invalid ID format");
            }
        } else {
            System.out.println("ID cannot be empty");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        
        dlmID.clear();
        dlmNama.clear();
        System.out.println("Display list reset");
        idDelete.setText("");
        namaDelete.setText("");
        idEdit.setText("");
        namaEdit.setText("");
        namaInput.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton ambilSemuaDataButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField idDelete;
    private javax.swing.JTextField idEdit;
    private javax.swing.JList<String> idList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField namaDelete;
    private javax.swing.JTextField namaEdit;
    private javax.swing.JTextField namaInput;
    private javax.swing.JList<String> namaList;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
